name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: cd to app
        run: cd app
      - name: Allow Scripts
        run:  cd app && chmod +x ./continuous_deployment/before_install.sh ./continuous_deployment/build.sh ./continuous_deployment/deploy.sh
      - name: Before Install
        run:  cd app && npm install
      - name: Install
        run:  cd app && npm test
      - name: Build
        run:  cd app && npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: app/build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: app/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: cd app && deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}